export const hotiDetails = [
  {
    id: "1",
    hindiName: "शा अचलचंद जवेरचंदजी",
    name: "ACHALCHANDJI JAVERCHANDJI BHIRLOSHA",
    city: "MYSORE",
    phone: "9886014697",
  },
  {
    id: "2",
    hindiName: "शा अमीचंद बाबुलालजी",
    name: "AMICHANDJI BABULALJI",
    city: "VIRAR",
    phone: "9271794618",
  },
  {
    id: "3",
    hindiName: "शा अरविंदकुमार मंछालालजी",
    name: "ARVINDKUMARJI MANCHALALJI",
    city: "AHMEDABAD",
    phone: "7023733696",
  },
  {
    id: "4",
    hindiName: "शा असलाजी भुताजी कोठारी",
    name: "ASALAJI BHUTAJI KOTHARI",
    city: "PERAMBALUR",
    phone: "9486067650",
  },
  {
    id: "5",
    hindiName: "शा अशोककुमार चम्पालालजी",
    name: "ASHOKUMARJI CHAMPALALJI",
    city: "JASWANTPURA",
    phone: "7506053516",
  },
  {
    id: "6",
    hindiName: "शा बाबूलाल असलाजी कोठारी",
    name: "BABULALJI ASALAJI KOTHARI",
    city: "KALLAKURICHI",
    phone: "9842652843",
  },
  {
    id: "7",
    hindiName: "शा बाबुलाल भिकाजी",
    name: "BABULALJI BHIKHAJI",
    city: "PUNE",
    phone: "9423581904",
  },
  {
    id: "8",
    hindiName: "शा बाबूलाल दानाजी",
    name: "BABULALJI DANAJI",
    city: "ANAND",
    phone: "9586129405",
  },
  {
    id: "9",
    hindiName: "शा बाबुलाल फुलचंदजी",
    name: "BABULALJI FULCHANDJI",
    city: "BORIVALI",
    phone: "7021082116",
  },
  {
    id: "10",
    hindiName: "शा बाबुलाल गजाजी मुथा",
    name: "BABULALJI GAJRAJJI MUTHA",
    city: "AHMEDABAD",
    phone: "9824014454",
  },
  {
    id: "11",
    hindiName: "शा बाबूलाल हुकमीचंदजी",
    name: "BABULALJI HUKMICHANDJI",
    city: "MUMBAI",
    phone: "9820174763",
  },
  {
    id: "12",
    hindiName: "शा बाबुलाल कस्तूरजी",
    name: "BABULALJI KASTURCHANDJI",
    city: "JAYSINGPUR",
    phone: "9420136888",
  },
  {
    id: "13",
    hindiName: "शा बाबुलाल मगाजी",
    name: "BABULALJI MAGAJI",
    city: "PUNE",
    phone: "7030593191",
  },
  {
    id: "14",
    hindiName: "शा बाबुलाल सोमाजी मुथा",
    name: "BABULALJI SOMAJI MUTHA",
    city: "PUNE",
    phone: "9890216450",
  },
  {
    id: "15",
    hindiName: "शा बाबुलाल भुराजी",
    name: "BABULALJI BHURAJI",
    city: "DAVANGIRI",
    phone: "9108614539",
  },
  {
    id: "16",
    hindiName: "शा बाबुलाल दानाजी(सिलदरवाला)",
    name: "BABULALJI DANAJI (SILDAR)",
    city: "MALAD",
    phone: "9820290828",
  },
  {
    id: "17",
    hindiName: "शा बखतावरमल सांकलाजी",
    name: "BAKHTAVARMALJI SAKALAJI",
    city: "MUMBAI",
    phone: "9321421061",
  },
  {
    id: "18",
    hindiName: "शा भबूतमल छोगालालजी",
    name: "BHABOOTMALJI CHHOGALALJI",
    city: "BORIVALI",
    phone: "9619638039",
  },
  {
    id: "19",
    hindiName: "शा भबूतमल धरमाजी ओसवाल",
    name: "BHABOOTMALJI DHARMAJI OSWAL",
    city: "KOLHAPUR",
    phone: "8007933033",
  },
  {
    id: "20",
    hindiName: "शा भबूतमल दोनाजी",
    name: "BHABUTMALJI DANMALJI",
    city: "UTTARSANDA",
    phone: "9925609545",
  },
  {
    id: "21",
    hindiName: "शा भबूतमल सांकलाजी",
    name: "BHABUTMALJI SAKALAJI",
    city: "ISLAMPUR",
    phone: "9421218656",
  },
  {
    id: "22",
    hindiName: "शा भरतकुमार उकचंदजी",
    name: "BHARATKUMARJI UKCHANDJI KOTHARI",
    city: "VADOD",
    phone: "9904051883",
  },
  {
    id: "23",
    hindiName: "शा भवरलाल पुनमचंदजी",
    name: "BHAVARLALJI PUNAMCHANDJI",
    city: "VIRAR",
    phone: "9320499241",
  },
  {
    id: "24",
    hindiName: "शा भुरमल छोगाजी",
    name: "BHURAMALJI CHHOGAJI",
    city: "ATTUR",
    phone: "9443427346",
  },
  {
    id: "25",
    hindiName: "शा भुरमल धरमाजी",
    name: "BHURMALJI  DHARMAJI",
    city: "MUMBAI",
    phone: "9833589202",
  },
  {
    id: "26",
    hindiName: "शा छगनलाल गेनमलजी",
    name: "CHAGANLALJI GENMALJI",
    city: "BHOR",
    phone: "8087011666",
  },
  {
    id: "27",
    hindiName: "शा छगनलाल प्रागाजी",
    name: "CHAGANLALJI PRAGAJI",
    city: "SASWAD",
    phone: "9403135787",
  },
  {
    id: "28",
    hindiName: "शा छगनलाल भुरमलजी",
    name: "CHAGANLALJI BHURMALJI",
    city: "BHYANDAR",
    phone: "9967743334",
  },
  {
    id: "29",
    hindiName: "शा चम्पालाल जवेरचंदजी",
    name: "CHAMPALALJI JAVERCHANDJI BHIRLOSHA",
    city: "MYSORE",
    phone: "9886466134",
  },
  {
    id: "30",
    hindiName: "शा चंदूलाल फुलचंदजी",
    name: "CHANDULALJI FULCHANDJI",
    city: "ICHALKARANJI",
    phone: "8999353792",
  },
  {
    id: "31",
    hindiName: "शा छोगालाल मगनलालजी",
    name: "CHOGALALJI MAGANLALJI",
    city: "CHENNAI",
    phone: "9884212321",
  },
  {
    id: "32",
    hindiName: "शा छोगमल हीराजी",
    name: "CHOGMALJI HIRAJI",
    city: "CHAKALASI",
    phone: "9909573024",
  },
  {
    id: "33",
    hindiName: "शा चौथमल लक्ष्मीचन्दजी",
    name: "CHOUTHMALJI LAXMICHANDJI MUTHA",
    city: "BORIVALI",
    phone: "9820378700",
  },
  {
    id: "34",
    hindiName: "शा चुनीलाल मगाजी कोठारी",
    name: "CHUNILALLJI MAGAJI KOTHARI(NIMBAJ)",
    city: "VIRAR",
    phone: "8550919769",
  },
  {
    id: "35",
    hindiName: "शा चुनीलाल असलाजी विक्रम प्रकाश",
    name: "CHUNILALJI ASLAJI-VIKRAM PRAKASH",
    city: "SURAT",
    phone: "9820960838",
  },
  {
    id: "36",
    hindiName: "शा चुनीलाल समनाजी कोठारी",
    name: "CHUNILALJI SAMANAAJI KOTHARI",
    city: "CUDDALORE",
    phone: "9443444870",
  },
  {
    id: "37",
    hindiName: "शा चूनीलाल धरमाजी ओसवाल",
    name: "CHUNILALJI DHARMAJI OSWAL",
    city: "PUNE",
    phone: "9822211332",
  },
  {
    id: "38",
    hindiName: "शा चूनीलाल सांकलाजी",
    name: "CHUNILALJI SAKALAJI",
    city: "JASWANTPURA",
    phone: "7666475850",
  },
  {
    id: "39",
    hindiName: "शा दानमल सांकलाजी",
    name: "DANMALJI SAKALAJI",
    city: "BORIVALI",
    phone: "9892100305",
  },
  {
    id: "40",
    hindiName: "शा दीपचंद गुलाबचन्दजी",
    name: "DEEPCHANDJI GULABCHANDJI",
    city: "BHYANDAR",
    phone: "9820559081",
  },
  {
    id: "41",
    hindiName: "शा दीपचंद सोपाजी",
    name: "DEEPCHANDJI SOPAJI",
    city: "MIRAJ",
    phone: "9890306638",
  },
  {
    id: "42",
    hindiName: "शा देवीचंद कस्तूरजी",
    name: "DEVICHANDJI KASTURJI",
    city: "BHRAMSAGAR",
    phone: "7353797761",
  },
  {
    id: "43",
    hindiName: "शा धनराज केसरीमलजी",
    name: "DHANRAJJI KESARIMAL MULAJI",
    city: "MYSORE",
    phone: "9740229777",
  },
  {
    id: "44",
    hindiName: "शा दिनेशकुमार चम्पालालजी",
    name: "DINESHKUMARJI CHAMPALALJI",
    city: "SURAT",
    phone: "9426138782",
  },
  {
    id: "45",
    hindiName: "शा दिनेशकुमार हंजारीमलजी",
    name: "DINESHKUMARJI HANJARIMALJI",
    city: "UMARGAON",
    phone: "9413123658",
  },
  {
    id: "46",
    hindiName: "शा डॉ.फूलचंद जेसाजी",
    name: "FULCHANDJI JAISAJI",
    city: "THANE",
    phone: "9022551234",
  },
  {
    id: "47",
    hindiName: "शा फूलचंद शंकरजी",
    name: "FULCHANDJI SHANKARJI (NOONWALA)",
    city: "BORIVALI",
    phone: "9619885392",
  },
  {
    id: "48",
    hindiName: "शा फुलचंद जवेरचंदजी",
    name: "FULCHANDJIJI JAVERCHANDJI BHIRLOSHA",
    city: "MYSORE",
    phone: "9845789428",
  },
  {
    id: "49",
    hindiName: "शा फूलचंद केसाजी मुथा",
    name: "FULCHANDJI KESAJI MUTHA",
    city: "PUNE",
    phone: "9975702546",
  },
  {
    id: "50",
    hindiName: "शा फूलचंद नेमीचंदजी",
    name: "FULCHANDJI NEMICHANDJI",
    city: "JASWANTPURA",
    phone: "8652522729",
  },
  {
    id: "51",
    hindiName: "शा फूलचंद सोमाजी मुथा",
    name: "FOOLCHANDJI SOMAJI MUTHA",
    city: "PUNE",
    phone: "9423003671",
  },
  {
    id: "52",
    hindiName: "शा गौतमकुमार हंजारीमलजी",
    name: "GAUTAMKUMARJI HANJARIMALJI GALBAJI",
    city: "JASWANTPURA",
    phone: "7568431061",
  },
  {
    id: "53",
    hindiName: "शा गेनमल हुकमीचंदजी",
    name: "GENMALJI HUKMICHANDJI",
    city: "AHMEDABAD",
    phone: "8511257759",
  },
  {
    id: "54",
    hindiName: "शा गेनमल जोरावरमलजी",
    name: "GENMALJI JORAWARJI",
    city: "SURAT",
    phone: "9427145766",
  },
  {
    id: "55",
    hindiName: "शा हंजारीमल भिकाजी",
    name: "HANJARIMALJI BHIKAJI",
    city: "PUNE",
    phone: "9822522558",
  },
  {
    id: "56",
    hindiName: "शा हंजारीमल कपूरजी",
    name: "HANJARIMALJI KAPURJI",
    city: "MYSORE",
    phone: "7829591863",
  },
  {
    id: "57",
    hindiName: "शा हंजारीमल केवाजी मुथा",
    name: "HANJARIMALJI KEWALCHANDJI  MUTHA",
    city: "BYADGI",
    phone: "9448309732",
  },
  {
    id: "58",
    hindiName: "शा हंजारीमल खुबाजी",
    name: "HANJARIMALJI KHUBAJI",
    city: "VIRAR",
    phone: "9821453264",
  },
  {
    id: "59",
    hindiName: "शा हंजारीमल विराजी",
    name: "HANJARIMALJI VIRAJI",
    city: "SURAT",
    phone: "9978851336",
  },
  {
    id: "60",
    hindiName: "शा हंजारीमल पुनमाजी मुथा",
    name: "HANJARIMALJI PUNMAJI MUTHA",
    city: "BHILWARA",
    phone: "8890211666",
  },
  {
    id: "61",
    hindiName: "शा हंसराज भुराजी मुथा",
    name: "HANSRAJ BHURAJI MUTHA",
    city: "PUNE",
    phone: "9422032606",
  },
  {
    id: "62",
    hindiName: "शा हेमचंद गेनमलजी",
    name: "HEMCHANDJI GENMALJI",
    city: "AHMEDABAD",
    phone: "9825920064",
  },
  {
    id: "63",
    hindiName: "शा हेमचंद गलालजी",
    name: "HEMCHANDJI GULALJI",
    city: "JAYSINGPUR",
    phone: "9867806128",
  },
  {
    id: "64",
    hindiName: "शा हेमराज वीरचंदजी",
    name: "HEMRAJJI VEERCHANDJI",
    city: "SURAT",
    phone: "9825160085",
  },
  {
    id: "65",
    hindiName: "शा हीराचन्द भुरमलजी",
    name: "HIRACHANDJI BHURMALJI",
    city: "KALYAN",
    phone: "8097959794",
  },
  {
    id: "66",
    hindiName: "शा जवेरचंद केसाजी मुथा",
    name: "JAVERCHANDJI KESAJI MUTHA",
    city: "JASWANTPURA",
    phone: "9822454818",
  },
  {
    id: "67",
    hindiName: "शा जयंतीलाल चुनिलालजी",
    name: "JAYANTILALJI CHUNILALJI",
    city: "TIRUNVALI",
    phone: "9500744723",
  },
  {
    id: "68",
    hindiName: "शा जेठमल गुलाबचन्दजी",
    name: "JETHMALJI GULABCHANDJI",
    city: "BORIVALI",
    phone: "9321497756",
  },
  {
    id: "69",
    hindiName: "शा जेठमल पुनमाजी कोठारी",
    name: "JETHMALJI  PUNAMAJI KOTHARI",
    city: "AHMEDABAD",
    phone: "9427960619",
  },
  {
    id: "70",
    hindiName: "शा जुगराज पुनमचंदजी",
    name: "JUGRAJJI  PUNAMCHANDJI",
    city: "BHYANDAR",
    phone: "9323351302",
  },
  {
    id: "71",
    hindiName: "शा कांतिलाल अमीचंदजी",
    name: "KANTILALJI  AMICHANDJI",
    city: "CHENNAI",
    phone: "8925417476",
  },
  {
    id: "72",
    hindiName: "शा कांतिलाल बाबुलालजी",
    name: "KANTILALJI  BABULALJI",
    city: "MYSORE",
    phone: "9448938666",
  },
  {
    id: "73",
    hindiName: "शा कांतिलाल छोगमलजी",
    name: "KANTILALJI  CHHOGMALJI",
    city: "AHMEDABAD",
    phone: "9913656983",
  },
  {
    id: "74",
    hindiName: "शा कांतिलाल लालचंदजी",
    name: "KANTILALJI  LALCHANDJI",
    city: "KALYAN",
    phone: "8879401617",
  },
  {
    id: "75",
    hindiName: "शा कांतिलाल पुनमचंदजी कोठारी",
    name: "KANTILALJI  PUNMAJI KOTHARI",
    city: "DAVANGIRI",
    phone: "9844255408",
  },
  {
    id: "76",
    hindiName: "शा कांतिलाल शंकरजी",
    name: "KANTILALJI  SHANKARJI",
    city: "TURAYUR",
    phone: "9443834013",
  },
  {
    id: "77",
    hindiName: "शा कांतिलाल हुकमीचंदजी",
    name: "KANTILALJI HUKMICHANDJI MUTHA",
    city: "AHMEDABAD",
    phone: "9428042956",
  },
  {
    id: "78",
    hindiName: "शा केसरीमल छोगाजी कोठारी",
    name: "KESARIMALJI  CHHOJAGI KOTHARI",
    city: "HOSDURGA",
    phone: "9886964543",
  },
  {
    id: "79",
    hindiName: "शा केसरीमल मुलाजी",
    name: "KESARIMALJI  MULAJI",
    city: "MYSORE",
    phone: "9845353755",
  },
  {
    id: "80",
    hindiName: "शा केवलचंद लक्ष्मीचन्दजी",
    name: "KEVALCHANDJI LAXMICHANDJI",
    city: "BORIVALI",
    phone: "9820383400",
  },
  {
    id: "81",
    hindiName: "शा खेमचंद पुनमचंदजी",
    name: "KHEMCHANDJI  PUNAMCHANDJI",
    city: "BORIVALI",
    phone: "9820562752",
  },
  {
    id: "82",
    hindiName: "शा खुमचंद पुनमाजी कोठारी",
    name: "KHUMCHANDJI PUNMAJI KOTHARI",
    city: "BANGALORE",
    phone: "7406432862",
  },
  {
    id: "83",
    hindiName: "शा खुमचंद पुनमाजी मुथा",
    name: "KHUMCHANDJI  PUNMAJI MUTHA",
    city: "PUNE",
    phone: "9420154922",
  },
  {
    id: "84",
    hindiName: "शा कुमारपाल भूबाजी",
    name: "KUMARPALJI  BHUBAJI",
    city: "BORIVALI",
    phone: "9820296162",
  },
  {
    id: "85",
    hindiName: "शा कुंदन डुंगरमलजी",
    name: "KUNDANJI  DUNGARMALJI RATNAJI",
    city: "GADHINGLAJ",
    phone: "9423841894",
  },
  {
    id: "86",
    hindiName: "शा लादूराम उकाजी",
    name: "LADURAMJI  UKAJI",
    city: "BHOR",
    phone: "9421000259",
  },
  {
    id: "87",
    hindiName: "शा लालचंद दानमलजी",
    name: "LALCHANDJI DANMALJI",
    city: "MYSORE",
    phone: "9844768908",
  },
  {
    id: "88",
    hindiName: "शा मफतलाल कस्तूरजी",
    name: "MAFATLALJI KASTURJI",
    city: "SURAT",
    phone: "9427148845",
  },
  {
    id: "89",
    hindiName: "शा मफतलाल उकाजी",
    name: "MAFATLALJI UKAJI",
    city: "BHYANDAR",
    phone: "8097583065",
  },
  {
    id: "90",
    hindiName: "शा मफतलाल हुकमीचंदजी",
    name: "MAFATLALJI HUKMICHANDJI",
    city: "BORIVALI",
    phone: "9029507547",
  },
  {
    id: "91",
    hindiName: "शा मफतलाल वनाजी",
    name: "MAFATLALJI VANAJI",
    city: "VIRAR",
    phone: "9920553499",
  },
  {
    id: "92",
    hindiName: "शा मगनलाल भिकाजी",
    name: "MAGANLALJI BHIKHAJI BHIRLOSHA",
    city: "MYSORE",
    phone: "8050050162",
  },
  {
    id: "93",
    hindiName: "शा मगनलाल भुबाजी",
    name: "MAGANLALJI BHUBAJI",
    city: "BORIVALI",
    phone: "9820520250",
  },
  {
    id: "94",
    hindiName: "शा मगनलाल समनाजी",
    name: "MAGANLALJI SAMANAJI",
    city: "PUNE",
    phone: "9822011052",
  },
  {
    id: "95",
    hindiName: "शा मगनलाल जेसाजी",
    name: "MAGANLALJI JAISAJI",
    city: "ICHALKARANJI",
    phone: "9421102785",
  },
  {
    id: "96",
    hindiName: "शा मगनलाल असलाजी",
    name: "MAGANLALJI ASLAJI",
    city: "SURAT",
    phone: "9377599246",
  },
  {
    id: "97",
    hindiName: "शा मगनलाल बाबुलालजी",
    name: "MAGANLALJI BABULALJI",
    city: "BHYANDAR",
    phone: "9892877887",
  },
  {
    id: "98",
    hindiName: "शा मगनलाल हिराजी",
    name: "MAGANLALJI HIRAJI",
    city: "AHMEDABAD",
    phone: "9323219224",
  },
  {
    id: "99",
    hindiName: "शा मगनलाल पुनमचंदजी मुथा",
    name: "MAGANLALJI PUNAMCHANDJI MUTHA",
    city: "VIRAR",
    phone: "9769414315",
  },
  {
    id: "100",
    hindiName: "शा महेंद्रकुमार छगनलालजी",
    name: "MAHENDRAKUMARJI CHAGANLALJI",
    city: "KALYAN",
    phone: "9892370011",
  },
  {
    id: "101",
    hindiName: "शा महेंद्रकुमार जीवराजजी",
    name: "MAHENDRAKUMARJI JIVRAJJI",
    city: "PUNE",
    phone: "9850143901",
  },
  {
    id: "102",
    hindiName: "शा मालचंद खुबाजी",
    name: "MALCHANDJI KHUBAJI",
    city: "MYSORE",
    phone: "9448055096",
  },
  {
    id: "103",
    hindiName: "शा मालचंद उकाजी",
    name: "MALCHANDJI UKAJI",
    city: "MYSORE",
    phone: "9886975883",
  },
  {
    id: "104",
    hindiName: "शा मालचंद हुकमीचंदजी",
    name: "MALCHANDJI HUKMICHANDJI MUTHA",
    city: "JASWANTPURA",
    phone: "7568206678",
  },
  {
    id: "105",
    hindiName: "शा मंछालाल धरमाजी ओसवाल",
    name: "MANCHALAL DHARMAJI OSWAL",
    city: "AMBARNATH",
    phone: "9323833904",
  },
  {
    id: "106",
    hindiName: "शा मंछालाल जवेरचंदजी",
    name: "MANCHALALJI JAVERCHANDJI",
    city: "BORIVALI",
    phone: "9323771265",
  },
  {
    id: "107",
    hindiName: "शा मंछालाल कस्तूरजी",
    name: "MANCHALALJI KASTURJI",
    city: "VIRAR",
    phone: "7387506166",
  },
  {
    id: "108",
    hindiName: "शा मंछालाल शंकरजी",
    name: "MANCHALALJI SHANKARJI",
    city: "ATTUR",
    phone: "9944314595",
  },
  {
    id: "109",
    hindiName: "शा मंछालाल छोगालालजी",
    name: "MANCHALALJI CHOGAJI",
    city: "BORIVALI",
    phone: "9619509382",
  },
  {
    id: "110",
    hindiName: "शा अशोककुमार मंछालालजी",
    name: "ASHKUMAR MANCHALALJI",
    city: "ICHALKARANJI",
    phone: "9423278540",
  },
  {
    id: "111",
    hindiName: "शा मंछालाल हिराजी",
    name: "MANCHHALALJI HIRAJI",
    city: "PUNE",
    phone: "9975077921",
  },
  {
    id: "112",
    hindiName: "शा मंगलचंद विसाजी",
    name: "MANGALCHANDJI VISAJI",
    city: "MYSORE",
    phone: "9886812685",
  },
  {
    id: "113",
    hindiName: "शा मणीलाल ओटमलजी",
    name: "MANILALJI OTMALJI",
    city: "JAYSINGPUR",
    phone: "8087377457",
  },
  {
    id: "114",
    hindiName: "शा मिश्रीमल चंपालालजी",
    name: "MISRIMALJI CHAMPALALJI",
    city: "SURAT",
    phone: "9869961846",
  },
  {
    id: "115",
    hindiName: "शा मोहनलाल छगनलालजी",
    name: "MOHANLALJI CHAGANLALJI",
    city: "PUNE",
    phone: "9595525101",
  },
  {
    id: "116",
    hindiName: "शा मोहनलाल चंपालालजी",
    name: "MOHANLALJI CHAMPALALJI",
    city: "BHYANDAR",
    phone: "7498992256",
  },
  {
    id: "117",
    hindiName: "शा मोहनलाल हंजारीमलजी",
    name: "MOHANLALJI HANJARIMALJI",
    city: "JASWANTPURA",
    phone: "9028311301",
  },
  {
    id: "118",
    hindiName: "शा मोहनलाल उकचंदजी कोठारी",
    name: "MOHANLALJI UKCHANDJI KOTHARI",
    city: "BHYANDAR",
    phone: "9969570174",
  },
  {
    id: "119",
    hindiName: "शा  मोहनलाल छोगमलजी",
    name: "MOHANLALJI CHHOGMALJI",
    city: "AHMEDABAD",
    phone: "9426369003",
  },
  {
    id: "120",
    hindiName: "शा मोहनलाल नथमलजी",
    name: "MOHANLALJI NATHMALJI",
    city: "BORIVALI",
    phone: "9323270949",
  },
  {
    id: "121",
    hindiName: "शा मोतीलाल कस्तूरजी",
    name: "MOTILALJI KASTURCHANDJI",
    city: "JAYSINGPUR",
    phone: "9422581822",
  },
  {
    id: "122",
    hindiName: "शा नरेशकुमार खेमचंदजी",
    name: "NARESHKUMARJI KHEMCHANDJI MUTHA",
    city: "BANGALORE",
    phone: "9844093621",
  },
  {
    id: "123",
    hindiName: "शा नथमल हुकमीचंदजी",
    name: "NATHMALJI HUKMICHANDJI MUTHA",
    city: "MYSORE",
    phone: "8105369400",
  },
  {
    id: "124",
    hindiName: "शा नवलमल दोनाजी",
    name: "NAVALMALJI DONAJI",
    city: "VIRAR",
    phone: "9324973691",
  },
  {
    id: "125",
    hindiName: "शा नवलमल कोनाजी",
    name: "NAVALMALJI KANAJI",
    city: "ICHALKARANJI",
    phone: "9987706844",
  },
  {
    id: "126",
    hindiName: "शा नवलमल जुठाजी मुथा",
    name: "NAVALMALJI JUTHAJI MUTHA",
    city: "NADIYAD",
    phone: "8149528243",
  },
  {
    id: "127",
    hindiName: "शा नवलमल उदाजी मुथा",
    name: "NAVALMALJI UDAJI MUTHA",
    city: "KOLHAPUR",
    phone: "9890116666",
  },
  {
    id: "128",
    hindiName: "शा नेमीचंद हंजारीमलजी",
    name: "NEMICHAND HANJARIMAL",
    city: "BYADGI",
    phone: "9448309732",
  },
  {
    id: "129",
    hindiName: "शा ओटमल समनाजी",
    name: "OTMALJI CHAMNAJI",
    city: "BANGALORE",
    phone: "9886190492",
  },
  {
    id: "130",
    hindiName: "शा पारसमल उदाजी",
    name: "PARASMALJI UDAJI",
    city: "MYSORE",
    phone: "9448938945",
  },
  {
    id: "131",
    hindiName: "शा पारसमल नथमलजी",
    name: "PARASMALJI NATMALJI",
    city: "BORIVALI",
    phone: "9819028235",
  },
  {
    id: "132",
    hindiName: "शा पारसमल शंकरलालजी",
    name: "PARASMALJI SHANKARLALJI",
    city: "KOLHAPUR",
    phone: "9422415951",
  },
  {
    id: "133",
    hindiName: "शा पोपटलाल गजाजी मुथा",
    name: "POPATLALJI GAJAJI MUTHA",
    city: "AHMEDABAD",
    phone: "9327071346",
  },
  {
    id: "134",
    hindiName: "शा प्रकाशचंद गेनमलजी",
    name: "PRAKASHCHANDJI GENMALJI",
    city: "AHMEDABAD",
    phone: "9510120136",
  },
  {
    id: "135",
    hindiName: "शा प्रकाशचंद खेतमलजी",
    name: "PRAKASHCHANDJI KHETMALJI",
    city: "JASWANTPURA",
    phone: "9960867139",
  },
  {
    id: "136",
    hindiName: "शा प्रकाशचंद बाबुलालजी",
    name: "PRAKASHMALJI BABULALJI MUTHA",
    city: "VIRAR",
    phone: "9869748710",
  },
  {
    id: "137",
    hindiName: "शा प्रतापचन्द केवाजी मुथा",
    name: "PRATAPCHANDJI KEWALCHANDJI  MUTHA",
    city: "DAVANGIRI",
    phone: "9448822830",
  },
  {
    id: "138",
    hindiName: "शा प्रतापचन्द ताराजी",
    name: "PRATAPCHANDJI TARAJI",
    city: "ICHALKARANJI",
    phone: "9404708735",
  },
  {
    id: "139",
    hindiName: "शा प्रवीण फुलचंदजी",
    name: "PRAVINJI FULCHANDJI BHURMALJI",
    city: "KALYAN",
    phone: "9870287459",
  },
  {
    id: "140",
    hindiName: "शा प्रेमचंद समनाजी",
    name: "PREMCHANDJI CHAMANAJI",
    city: "VARDACHALAM",
    phone: "8940019080",
  },
  {
    id: "141",
    hindiName: "शा प्रेमचंद शंकरजी",
    name: "PREMCHANDJI SHANKARJI",
    city: "JASWANTPURA",
    phone: "8619464641",
  },
  {
    id: "142",
    hindiName: "शा प्रेमचंद विराजी",
    name: "PREMCHANDJI VIRAJI",
    city: "DAVANGIRI",
    phone: "9448980215",
  },
  {
    id: "143",
    hindiName: "शा पुखराज नेमीचंदजी",
    name: "PUKHRAJJI NEMICHANDJI",
    city: "VIRAR",
    phone: "9322386623",
  },
  {
    id: "144",
    hindiName: "शा पुखराज वीरचंदजी(सिलदरवाला)",
    name: "PUKHRAJJI VIRCHANDGI (SILDAR)",
    city: "DHARAMPURI",
    phone: "9844973358",
  },
  {
    id: "145",
    hindiName: "शा पुखराज विसाजी",
    name: "PUKHRAJJI VISAJI",
    city: "MYSORE",
    phone: "9980798632",
  },
  {
    id: "146",
    hindiName: "शा पुखराज हेमचंदजी",
    name: "PUKHRAJJI HEMCHANDJI",
    city: "BHYANDAR",
    phone: "8239091392",
  },
  {
    id: "147",
    hindiName: "शा पुखराज जवेरचंदजी",
    name: "PUKHRAJJI JAVERCHANDJI",
    city: "VIRAR",
    phone: "9890663788",
  },
  {
    id: "148",
    hindiName: "शा पुनमचंद खेताजी",
    name: "PUNAMCHANDJI KHETAJI MUTHA",
    city: "PUNE",
    phone: "9413818923",
  },
  {
    id: "149",
    hindiName: "शा पुनमचंद लुंबाजी",
    name: "PUNAMCHANDJI LUMBAJI",
    city: "JAYSINGPUR",
    phone: "9423225608",
  },
  {
    id: "150",
    hindiName: "शा पुनमचंद ताराजी",
    name: "PUNAMCHANDJI TARAJI",
    city: "ICHALKARANJI",
    phone: "9422580449",
  },
  {
    id: "151",
    hindiName: "शा राजेन्द्रकुमार देवीचंदजी",
    name: "RAJENDRAKUMARJI DEVICHANDJI",
    city: "RANEBENNUR",
    phone: "9480323258",
  },
  {
    id: "152",
    hindiName: "शा राजमल दानाजी",
    name: "RAJMALJI DANMALJI",
    city: "BHYANDAR",
    phone: "9768313174",
  },
  {
    id: "153",
    hindiName: "शा रमणकुमार मंछालालजी",
    name: "RAMANKUMARJI MANCHALALJI",
    city: "AHMEDABAD",
    phone: "9426579583",
  },
  {
    id: "154",
    hindiName: "शा रमेशचंद लक्ष्मीचन्दजी",
    name: "RAMESHCHANDJI LAXMICHANDJI MUTHA",
    city: "BORIVALI",
    phone: "9820029097",
  },
  {
    id: "155",
    hindiName: "शा रमेशकुमार दानमलजी",
    name: "RAMESHKUMARJI DANMALJI",
    city: "MYSORE",
    phone: "9844243725",
  },
  {
    id: "156",
    hindiName: "शा रमेशकुमार फुलचंदजी",
    name: "RAMESHKUMARJI PHULCHANDJI",
    city: "ICHALKARANJI",
    phone: "9422073920",
  },
  {
    id: "157",
    hindiName: "शा रमेशकुमार हंसाजी कोठारी",
    name: "RAMESHKUMARJI HANSAJI KOTHARI",
    city: "PUNE",
    phone: "9764575555",
  },
  {
    id: "158",
    hindiName: "शा रमेशकुमार जीवराजजी",
    name: "RAMESHKUMARJI JIVRAJJI-DIXIT",
    city: "PUNE",
    phone: "9151517979",
  },
  {
    id: "159",
    hindiName: "शा रमेशकुमार कपूरचंदजी",
    name: "RAMESHKUMARJI KAPOORCHANDJI",
    city: "MYSORE",
    phone: "9845472162",
  },
  {
    id: "160",
    hindiName: "शा रमेशकुमार मंछालालजी",
    name: "RAMESHKUMARJI MANCHALALJI",
    city: "VIRAR",
    phone: "9322226402",
  },
  {
    id: "161",
    hindiName: "शा रमेशकुमार पुनमचंदजी कोठारी",
    name: "RAMESHKUMARJI PUNMAJI KOTHARI",
    city: "VIRAR",
    phone: "9819532561",
  },
  {
    id: "162",
    hindiName: "शा रमेशकुमार उकचंदजी कोठारी",
    name: "RAMESHKUMARJI UKCHANDJI KOTHARI",
    city: "VADOD",
    phone: "9825335349",
  },
  {
    id: "163",
    hindiName: "शा रमेशकुमार वरदीचंदजी",
    name: "RAMESHKUMARJI VARDICHANDJI",
    city: "MUMBAI",
    phone: "9867261096",
  },
  {
    id: "164",
    hindiName: "शा रमेशकुमार वीरचंदजी",
    name: "RAMESHKUMARJI VIRCHANDJI",
    city: "SURAT",
    phone: "9978489386",
  },
  {
    id: "165",
    hindiName: "शा रतनचंद पुनमाजी",
    name: "RATANCHANDJI PUNMAJI",
    city: "MYSORE",
    phone: "9538401308",
  },
  {
    id: "166",
    hindiName: "शा रतनचंद असलाजी",
    name: "RATANCHANDJI ASLAJI",
    city: "MYSORE",
    phone: "9343057065",
  },
  {
    id: "167",
    hindiName: "शा रतनचंद जवेरचंदजी",
    name: "RATANCHANDJI JAVERCHANDJI MUTHA",
    city: "VIRAR",
    phone: "9324362211",
  },
  {
    id: "168",
    hindiName: "शा रिखबचंद रतनाजी",
    name: "RIKABCHANDJI RATNAJI",
    city: "BHYANDAR",
    phone: "9867087968",
  },
  {
    id: "169",
    hindiName: "शा रिखबचंद मंछालालजी",
    name: "RIKHABCHANDJI MANCHHALALJI",
    city: "VIRAR",
    phone: "9320055830",
  },
  {
    id: "170",
    hindiName: "शा साकलचंद हंसाजी",
    name: "SAKALCHANDJI HANSAJI",
    city: "MYSORE",
    phone: "8050797585",
  },
  {
    id: "171",
    hindiName: "शा सांकलचंद गलालजी",
    name: "SAKALCHANDJI GULALJI",
    city: "JAYSINGPUR",
    phone: "9423275801",
  },
  {
    id: "172",
    hindiName: "संघवी शा गेनमल वरदीचंदजी",
    name: "SANGHVI  GENMALJI VARDICHANDJI",
    city: "SURAT",
    phone: "9426887427",
  },
  {
    id: "173",
    hindiName: "संघवी शा गुलाबचंद जवेरजी",
    name: "SANGHVI  GULABCHANDJI JAVERJI",
    city: "JAYSINGPUR",
    phone: "9422045027",
  },
  {
    id: "174",
    hindiName: "संघवी शा कपूरचंद मगनलालजी",
    name: "SANGHVI  KAPURCHANDJI MAGANLALJI",
    city: "MUMBAI",
    phone: "9820560769",
  },
  {
    id: "175",
    hindiName: "संघवी शा फुलचंद वरदीचंदजी",
    name: "SANGHVI  FULCHANDJI VARDICHANDJI",
    city: "SURAT",
    phone: "9426433931",
  },
  {
    id: "176",
    hindiName: "संघवी शा पिथालाल सांकलाजी",
    name: "SANGHVI  PITHALALJI SAKALAJI KOTHARI",
    city: "PUNE",
    phone: "9764429278",
  },
  {
    id: "177",
    hindiName: "संघवी शा पृथ्वीराज मगनलालजी",
    name: "SANGHVI  PRITHVIRAJJI MAGANLALJI",
    city: "CHENNAI",
    phone: "9840249749",
  },
  {
    id: "178",
    hindiName: "संघवी शा शंकरलाल जवेरजी",
    name: "SANGHVI SHANKARLALJI  JAVERJI",
    city: "MUMBAI",
    phone: "9892891555",
  },
  {
    id: "179",
    hindiName: "संघवी शा केसरीमल बाबुलालजी",
    name: "SANGHVI KESARIMALJI BABULALJI",
    city: "VILEPARLE",
    phone: "9969253002",
  },
  {
    id: "180",
    hindiName: "शा शंकरलाल धरमाजी पोरवाल",
    name: "SHANKARLALJI DHARMAJI PORWAL",
    city: "ATTUR",
    phone: "9790160214",
  },
  {
    id: "181",
    hindiName: "शा शंकरलाल भलाजी",
    name: "SHANKARLALJI BHALAJI (BANSILAL)",
    city: "CHAKALASI",
    phone: "7874491339",
  },
  {
    id: "182",
    hindiName: "शा शंकरलाल हुकमीचंदजी",
    name: "SHANKARLALJI HUKMICHANDJI MUTHA",
    city: "AHMEDABAD",
    phone: "9408822870",
  },
  {
    id: "183",
    hindiName: "शा शंकरलाल हंसाजी मुथा",
    name: "SHANKARLALJI HANSAJI MUTHA",
    city: "KOLHAPUR",
    phone: "9422049575",
  },
  {
    id: "184",
    hindiName: "शा शांतिलाल असलाजी",
    name: "SHANTILALJI ASLAJI-MANOJ",
    city: "BHYANDAR",
    phone: "9930185640",
  },
  {
    id: "185",
    hindiName: "शा शांतिलाल गुलाबचन्दजी",
    name: "SHANTILALJI GULABCHANDJI",
    city: "DAHISAR",
    phone: "9821345529",
  },
  {
    id: "186",
    hindiName: "शा शांतिलाल जवेरचंदजी",
    name: "SHANTILALJI JAVERCHANDJI BHIRLOSHA",
    city: "MYSORE",
    phone: "9342183092",
  },
  {
    id: "187",
    hindiName: "शा शांतिलाल जोरावरमलजी",
    name: "SHANTILALJI JORAJI",
    city: "MYSORE",
    phone: "9743180821",
  },
  {
    id: "188",
    hindiName: "शा शांतिलाल मगनलालजी",
    name: "SHANTILALJI MAGANLALJI",
    city: "PUNE",
    phone: "9422030733",
  },
  {
    id: "189",
    hindiName: "शा शांतिलाल रतनाजी",
    name: "SHANTILALJI RATNAJI",
    city: "GADHINGLAJ",
    phone: "9822108434",
  },
  {
    id: "190",
    hindiName: "शा शांतिलाल शंकरजी",
    name: "SHANTILALJI SHANKARJI",
    city: "BORIVALI",
    phone: "9820071565",
  },
  {
    id: "191",
    hindiName: "शा शांतिलाल भिकाजी",
    name: "SHANTILALJI BHIKHAJI BHIRLOSHA",
    city: "MYSORE",
    phone: "9916182501",
  },
  {
    id: "192",
    hindiName: "शा शिवलाल बाबुलालजी",
    name: "SHIVLALJI BABULALJI",
    city: "BHYANDAR",
    phone: "7498099001",
  },
  {
    id: "193",
    hindiName: "शा शिवलाल केवाजी मुथा",
    name: "SHIVLALJI KEWALCHANDJI  MUTHA",
    city: "DAVANGIRI",
    phone: "9448534923",
  },
  {
    id: "194",
    hindiName: "शा शिवलाल केसाजी",
    name: "SHIVLALJI KESAJI",
    city: "VIRAR",
    phone: "9730789946",
  },
  {
    id: "195",
    hindiName: "शा शिवलाल पुनमाजी",
    name: "SHIVLALJI PUNMAJI",
    city: "VIRAR",
    phone: "9158089935",
  },
  {
    id: "196",
    hindiName: "शा सोहनलाल नथमलजी",
    name: "SOHANLALJI NATHMALJI",
    city: "BORIVALI",
    phone: "9833603322",
  },
  {
    id: "197",
    hindiName: "शा सुखराज अमीचंदजी",
    name: "SUKHRAJJI AMICHANDJI",
    city: "UMARGAON",
    phone: "9898349830",
  },
  {
    id: "198",
    hindiName: "शा सुरेशकुमार हिराचंदजी",
    name: "SURESHKUMARJI HIRACHANDJI",
    city: "MYSORE",
    phone: "9449271547",
  },
  {
    id: "199",
    hindiName: "शा सुरेशकुमार खेतमलजी",
    name: "SURESHKUMARJI KHETMALJI",
    city: "MUMBAI",
    phone: "8454858478",
  },
  {
    id: "200",
    hindiName: "शा सुरेशकुमार पुनमचंदजी",
    name: "SURESHKUMARJI PUNMAJI",
    city: "VIRAR",
    phone: "9323640040",
  },
  {
    id: "201",
    hindiName: "शा सुरेशकुमार उदाजी",
    name: "SURESHKUMARJI UDAJI",
    city: "BHYANDAR",
    phone: "9967861017",
  },
  {
    id: "202",
    hindiName: "शा स्वरूपचंद फुलचंदजी",
    name: "SWARUPCHANDJI PHULCHANDJI",
    city: "ICHALKARANJI",
    phone: "9423286140",
  },
  {
    id: "203",
    hindiName: "शा ताराचंद भुराजी मुथा",
    name: "TARACHANDJI BHURAJI MUTHA",
    city: "PUNE",
    phone: "9423533570",
  },
  {
    id: "204",
    hindiName: "शा ताराचंद छोगाजी",
    name: "TARACHANDJI CHOGAJI",
    city: "MUMBAI",
    phone: "9820289542",
  },
  {
    id: "205",
    hindiName: "शा ताराचंद गुलाबचन्दजी",
    name: "TARACHANDJI GULABCHANDJI",
    city: "DAHISAR",
    phone: "8097458809",
  },
  {
    id: "206",
    hindiName: "शा ताराचंद पुनमाजी मुथा",
    name: "TARACHANDJI PUNMAJI MUTHA",
    city: "VIRAR",
    phone: "9421620427",
  },
  {
    id: "207",
    hindiName: "शा ताराचंद शिवलालजी मेहता",
    name: "TARACHANDJI SHIVLALJI METHA",
    city: "MUMBAI",
    phone: "9821166237",
  },
  {
    id: "208",
    hindiName: "शा तेजपाल पुनमाजी कोठारी",
    name: "TEJRAJJI PUNMAJI KOTHARI",
    city: "AHMEDABAD",
    phone: "9428806429",
  },
  {
    id: "209",
    hindiName: "शा तेजराज पुनमाजी कोठारी",
    name: "TEJPALJI PUNMAJI KOTHARI",
    city: "SURAT",
    phone: "9427120287",
  },
  {
    id: "210",
    hindiName: "शा उदयराज खेतमलजी",
    name: "UDAYRAJJI KHETMALJI",
    city: "VIRAR",
    phone: "9324359220",
  },
  {
    id: "211",
    hindiName: "शा उकचंद मुलाजी",
    name: "UKCHANDJI MULAJI",
    city: "MYSORE",
    phone: "9738547585",
  },
  {
    id: "212",
    hindiName: "शा उकचंद पीथाजी मुथा",
    name: "UKCHANDJI PITHAJI MUTHA",
    city: "PUNE",
    phone: "9422024106",
  },
  {
    id: "213",
    hindiName: "शा उकचंद शंकरलालजी",
    name: "UKCHANDJI SHANKARLALJI",
    city: "PUNE",
    phone: "9371012880",
  },
  {
    id: "214",
    hindiName: "शा उकचंद उदाजी मुथा",
    name: "UKCHANDJI UDAJI MUTHA",
    city: "KOLHAPUR",
    phone: "9423354999",
  },
  {
    id: "215",
    hindiName: "शा उनमल कपूरजी",
    name: "UNMALJI KAPURJI BHIRLOSHA",
    city: "MYSORE",
    phone: "9448054803",
  },
  {
    id: "216",
    hindiName: "शा उनमल लादाजी",
    name: "UNMALJI LADAJI",
    city: "PERNA FATA",
    phone: "9586876629",
  },
  {
    id: "217",
    hindiName: "शा वगतावरमल बाबुलालजी",
    name: "VAGTAVARMALJI BABULALJI OSWAL",
    city: "CHENNAI",
    phone: "7401002129",
  },
  {
    id: "218",
    hindiName: "शा वरदीचंद असलाजी",
    name: "VARDICHANDJI ASLAJI",
    city: "BHYANDAR",
    phone: "9969702648",
  },
  {
    id: "219",
    hindiName: "शा वरदीचंद चुनिलालजी",
    name: "VARDICHANDJI CHUNILALJI",
    city: "PUNE",
    phone: "9422047031",
  },
  {
    id: "220",
    hindiName: "शा वरदीचंद केवलचंदजी मुथा",
    name: "VARDICHANDJI KEWALCHANDJI MUTHA",
    city: "BYADGI",
    phone: "9448119561",
  },
  {
    id: "221",
    hindiName: "शा वरदीचंद पुनमचंदजी कोठारी",
    name: "VARDICHANDJI PUNMAJI KOTHARI",
    city: "JASWANTPURA",
    phone: "9571842789",
  },
  {
    id: "222",
    hindiName: "शा वरदीचंद हिराजी",
    name: "VARDICHANDJI HIRAJI",
    city: "UMARGAON",
    phone: "9033447204",
  },
  {
    id: "223",
    hindiName: "शा वीरचंद असलाजी",
    name: "VEERCHANDJI ASLAJI",
    city: "SURAT",
    phone: "7878715790",
  },
  {
    id: "224",
    hindiName: "शा वीरचंद भुबाजी",
    name: "VIRCHANDJI BHUBAJI",
    city: "SURAT",
    phone: "8141889830",
  },
  {
    id: "301",
    hindiName: "शा चंपालालजी बाड़मेरीया",
    name: "CHAMPALALJI BADMERIYA",
    city: "JASWANTPURA",
    phone: "7757994451",
  },
  {
    id: "302",
    hindiName: "शा राजू बाड़मेरीया",
    name: "RAJU BADMERIYA",
    city: "JASWANTPURA",
    phone: "9422583414",
  },
];
