export const labhartiDetails = [
  {
    hotiId: 1,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "ACHALCHANDJI JAVERCHANDJI BHIRLOSHA",
  },
  {
    hotiId: 2,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "AMICHANDJI BABULALJI",
  },
  {
    hotiId: 3,
    hotiTicketQuota: 1,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "ARVINDKUMAR MANCHALALJI",
  },
  {
    hotiId: 4,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "ASALAJI BHUTAJI KOTHARI",
  },
  {
    hotiId: 5,
    hotiTicketQuota: 1,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "ASHOKUMARJI CHAMPALALJI",
  },
  {
    hotiId: 6,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 0,
    hotiName: "BABULALJI ASALAJI KOTHARI",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 7,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "BABULALJI BHIKHAJI",
  },
  {
    hotiId: 8,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "BABULALJI DANAJI",
  },
  {
    hotiId: 9,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 2,
    hotiName: "BABULALJI FULCHANDJI",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 10,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 11,
    extraTicketQuota: 6,
    hotiName: "BABULALJI GAJRAJJI MUTHA",
    contributionInRupees: 1100000,
    labhartiType: "Swarna",
  },
  {
    hotiId: 11,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 0,
    hotiName: "BABULALJI HUKMICHANDJI",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 12,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 2,
    hotiName: "BABULALJI KASTURCHANDJI",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 13,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "BABULALJI MAGAJI",
  },
  {
    hotiId: 14,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "BABULALJI SOMAJI MUTHA",
  },
  {
    hotiId: 15,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "BABULALJI BHURAJI",
  },
  {
    hotiId: 16,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 5,
    hotiName: "BABULALJI DANAJI (SILDAR)",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 17,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 2,
    hotiName: "BAKHTAVARMALJI SAKALAJI",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 18,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 11,
    extraTicketQuota: 6,
    hotiName: "BHABOOTMALJI CHHOGALALJI",
    contributionInRupees: 1100000,
    labhartiType: "Swarna",
  },
  {
    hotiId: 19,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "BHABOOTMALJI DHARMAJI OSWAL",
  },
  {
    hotiId: 20,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "BHABUTMALJI DANMALJI",
  },
  {
    hotiId: 21,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "BHABUTMALJI SAKALAJI",
  },
  {
    hotiId: 22,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "BHARATKUMARJI UKCHANDJI KOTHARI",
  },
  {
    hotiId: 23,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "BHAVARLALJI PUNAMCHANDJI",
  },
  {
    hotiId: 24,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 2,
    hotiName: "BHURAMALJI CHHOGAJI",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 25,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "BHURMALJI  DHARMAJI",
  },
  {
    hotiId: 26,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "CHAGANLALJI GENMALJI",
  },
  {
    hotiId: 27,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "CHAGANLALJI PRAGAJI",
  },
  {
    hotiId: 28,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 1,
    hotiName: "CHAGANLALJI BHURMALJI",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 29,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "CHAMPALALJI JAVERCHANDJI BHIRLOSHA",
  },
  {
    hotiId: 30,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "CHANDULALJI FULCHANDJI",
  },
  {
    hotiId: 31,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 1,
    hotiName: "CHOGALALJI MAGANLALJI",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 32,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "CHOGMALJI HIRAJI",
  },
  {
    hotiId: 33,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 4,
    hotiName: "CHOUTHMALJI LAXMICHANDJI MUTHA",
  },
  {
    hotiId: 34,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "CHUNILALLJI MAGAJI KOTHARI(NIMBAJ)",
  },
  {
    hotiId: 35,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "CHUNILALJI ASLAJI-VIKRAM PRAKASH",
  },
  {
    hotiId: 36,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 21,
    extraTicketQuota: 10,
    hotiName: "CHUNILALJI SAMANAAJI KOTHARI",
    contributionInRupees: 2100000,
    labhartiType: "Hirak",
  },
  {
    hotiId: 37,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "CHUNILALJI DHARMAJI OSWAL",
  },
  {
    hotiId: 38,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "CHUNILALJI SAKALAJI",
  },
  {
    hotiId: 39,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 1,
    hotiName: "DANMALJI SAKALAJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 40,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 5,
    hotiName: "DEEPCHANDJI GULABCHANDJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 41,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "DEEPCHANDJI SOPAJI",
  },
  {
    hotiId: 42,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "DEVICHANDJI KASTURJI",
  },
  {
    hotiId: 43,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "DHANRAJJI KESARIMAL MULAJI",
  },
  {
    hotiId: 44,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "DINESHKUMARJI CHAMPALALJI",
  },
  {
    hotiId: 45,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "DINESHKUMARJI HANJARIMALJI",
  },
  {
    hotiId: 46,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "FULCHANDJI JAISAJI",
  },
  {
    hotiId: 47,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "FULCHANDJI SHANKARJI (NOONWALA)",
  },
  {
    hotiId: 48,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "FULCHANDJIJI JAVERCHANDJI BHIRLOSHA",
  },
  {
    hotiId: 49,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "FULCHANDJI KESAJI MUTHA",
  },
  {
    hotiId: 50,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "FULCHANDJI NEMICHANDJI",
  },
  {
    hotiId: 51,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "FOOLCHANDJI SOMAJI MUTHA",
  },
  {
    hotiId: 52,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "GAUTAMKUMARJI HANJARIMALJI GALBAJI",
  },
  {
    hotiId: 53,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 6,
    hotiName: "GENMALJI HUKMICHANDJI",
  },
  {
    hotiId: 54,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "GENMALJI JORAWARJI",
  },
  {
    hotiId: 55,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "HANJARIMALJI BHIKAJI",
  },
  {
    hotiId: 56,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 7,
    hotiName: "HANJARIMALJI KAPURJI",
  },
  {
    hotiId: 57,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "HANJARIMALJI KEWALCHANDJI  MUTHA",
  },
  {
    hotiId: 58,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "HANJARIMALJI KHUBAJI",
  },
  {
    hotiId: 59,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "HANJARIMALJI VIRAJI",
  },
  {
    hotiId: 60,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "HANJARIMALJI PUNMAJI MUTHA",
  },
  {
    hotiId: 61,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 0,
    hotiName: "HANSRAJ BHURAJI MUTHA",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 62,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "HEMCHANDJI GENMALJI",
  },
  {
    hotiId: 63,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "HEMCHANDJI GULALJI",
  },
  {
    hotiId: 64,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "HEMRAJJI VEERCHANDJI",
  },
  {
    hotiId: 65,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 11,
    extraTicketQuota: 0,
    hotiName: "HIRACHANDJI BHURMALJI",
    contributionInRupees: 1100000,
    labhartiType: "Swarna",
  },
  {
    hotiId: 66,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "JAVERCHANDJI KESAJI MUTHA",
  },
  {
    hotiId: 67,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "JAYANTILALJI CHUNILALJI",
  },
  {
    hotiId: 68,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 4,
    hotiName: "JETHMALJI GULABCHANDJI",
  },
  {
    hotiId: 69,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "JETHMALJI  PUNAMAJI KOTHARI",
  },
  {
    hotiId: 70,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "JUGRAJJI  PUNAMCHANDJI",
  },
  {
    hotiId: 71,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "KANTILALJI  AMICHANDJI",
  },
  {
    hotiId: 72,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "KANTILALJI  BABULALJI",
  },
  {
    hotiId: 73,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "KANTILALJI  CHHOGMALJI",
  },
  {
    hotiId: 74,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "KANTILALJI  LALCHANDJI",
  },
  {
    hotiId: 75,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "KANTILALJI  PUNMAJI KOTHARI",
  },
  {
    hotiId: 76,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 2,
    hotiName: "KANTILALJI  SHANKARJI",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 77,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "KANTILALJI HUKMICHANDJI MUTHA",
  },
  {
    hotiId: 78,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "KESARIMALJI  CHHOJAGI KOTHARI",
  },
  {
    hotiId: 79,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "KESARIMALJI  MULAJI",
  },
  {
    hotiId: 80,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 4,
    hotiName: "KEVALCHANDJI LAXMICHANDJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 81,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 2,
    hotiName: "KHEMCHANDJI  UKCHANDJI",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 82,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "KHUMCHANDJI PUNMAJI KOTHARI",
  },
  {
    hotiId: 83,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "KHUMCHANDJI  PUNMAJI MUTHA",
  },
  {
    hotiId: 84,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 3,
    hotiName: "KUMARPALJI  BHUBAJI",
  },
  {
    hotiId: 85,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 4,
    hotiName: "KUNDANJI  DUNGARMALJI RATNAJI",
  },
  {
    hotiId: 86,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "LADURAMJI  UKAJI",
  },
  {
    hotiId: 87,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "LALCHANDJI DANMALJI",
  },
  {
    hotiId: 88,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MAFATLALJI KASTURJI",
  },
  {
    hotiId: 89,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MAFATLALJI UKAJI",
  },
  {
    hotiId: 90,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MAFATLALJI HUKMICHANDJI",
  },
  {
    hotiId: 91,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MAFATLALJI VANAJI",
  },
  {
    hotiId: 92,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "MAGANLALJI BHIKHAJI BHIRLOSHA",
  },
  {
    hotiId: 93,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 1,
    hotiName: "MAGANLALJI BHUBAJI",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 94,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 8,
    hotiName: "MAGANLALJI SAMANAJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 95,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 4,
    hotiName: "MAGANLALJI JAISAJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 96,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MAGANLALJI ASLAJI",
  },
  {
    hotiId: 97,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "MAGANLALJI BABULALJI",
  },
  {
    hotiId: 98,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MAGANLALJI HIRAJI",
  },
  {
    hotiId: 99,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "MAGANLALJI PUNAMCHANDJI MUTHA",
  },
  {
    hotiId: 100,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MAHENDRAKUMARJI CHAGANLALJI",
  },
  {
    hotiId: 101,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "MAHENDRAKUMARJI JIVRAJJI",
  },
  {
    hotiId: 102,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 3,
    hotiName: "MALCHANDJI KHUBAJI",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 103,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "MALCHANDJI UKAJI",
  },
  {
    hotiId: 104,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "MALCHANDJI HUKMICHANDJI MUTHA",
  },
  {
    hotiId: 105,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MANCHALAL DHARMAJI OSWAL",
  },
  {
    hotiId: 106,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "MANCHALALJI JAVERCHANDJI",
  },
  {
    hotiId: 107,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "MANCHALALJI KASTURJI",
  },
  {
    hotiId: 108,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 5,
    hotiName: "MANCHALALJI SHANKARJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 109,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MANCHALALJI CHOGAJI",
  },
  {
    hotiId: 110,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "ASHKUMAR MANCHALALJI",
  },
  {
    hotiId: 111,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "MANCHHALALJI HIRAJI",
  },
  {
    hotiId: 112,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "MANGALCHANDJI VISAJI",
  },
  {
    hotiId: 113,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MANILALJI OTMALJI",
  },
  {
    hotiId: 114,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "MISRIMALJI CHAMPALALJI",
  },
  {
    hotiId: 115,
    hotiTicketQuota: 1,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MOHANLALJI CHAGANLALJI",
  },
  {
    hotiId: 116,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 2,
    hotiName: "MOHANLALJI CHAMPALALJI",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 117,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MOHANLALJI HANJARIMALJI",
  },
  {
    hotiId: 118,
    hotiTicketQuota: 1,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "MOHANLALJI UKCHANDJI KOTHARI",
  },
  {
    hotiId: 119,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 3,
    hotiName: "MOHANLALJI CHHOGMALJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 120,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "MOHANLALJI NATHMALJI",
  },
  {
    hotiId: 121,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "MOTILALJI KASTURCHANDJI",
  },
  {
    hotiId: 122,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "NARESHKUMARJI KHEMCHANDJI MUTHA",
  },
  {
    hotiId: 123,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "NATHMALJI HUKMICHANDJI MUTHA",
  },
  {
    hotiId: 124,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 5,
    hotiName: "NAVALMALJI DONAJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 125,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "NAVALMALJI KANAJI",
  },
  {
    hotiId: 126,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "NAVALMALJI JUTHAJI MUTHA",
  },
  {
    hotiId: 127,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 7,
    hotiName: "NAVALMALJI UDAJI MUTHA",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 128,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "SHAH NEMICHAND HANJARIMAL JI",
  },
  {
    hotiId: 129,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "OTMALJI CHAMNAJI",
  },
  {
    hotiId: 130,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "PARASMALJI UDAJI",
  },
  {
    hotiId: 131,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PARASMALJI NATMALJI",
  },
  {
    hotiId: 132,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PARASMALJI SHANKARLALJI",
  },
  {
    hotiId: 133,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 6,
    hotiName: "POPATLALJI GAJAJI MUTHA",
  },
  {
    hotiId: 134,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "PRAKASHCHANDJI GENMALJI",
  },
  {
    hotiId: 135,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "PRAKASHCHANDJI KHETMALJI",
  },
  {
    hotiId: 136,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 2,
    hotiName: "PRAKASHMALJI BABULALJI MUTHA",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 137,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PRATAPCHANDJI KEWALCHANDJI  MUTHA",
  },
  {
    hotiId: 138,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PRATAPCHANDJI TARAJI",
  },
  {
    hotiId: 139,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "PRAVINJI FULCHANDJI BHURMALJI",
  },
  {
    hotiId: 140,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PREMCHANDJI CHAMANAJI",
  },
  {
    hotiId: 141,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "PREMCHANDJI SHANKARJI",
  },
  {
    hotiId: 142,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PREMCHANDJI VIRAJI",
  },
  {
    hotiId: 143,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 4,
    hotiName: "PUKHRAJJI NEMICHANDJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 144,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PUKHRAJJI VIRCHANDGI (SILDAR)",
  },
  {
    hotiId: 145,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PUKHRAJJI VISAJI",
  },
  {
    hotiId: 146,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "PUKHRAJJI HEMCHANDJI",
  },
  {
    hotiId: 147,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PUKHRAJJI JAVERCHANDJI",
  },
  {
    hotiId: 148,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "PUNAMCHANDJI KHETAJI MUTHA",
  },
  {
    hotiId: 149,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PUNAMCHANDJI LUMBAJI",
  },
  {
    hotiId: 150,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "PUNAMCHANDJI TARAJI",
  },
  {
    hotiId: 151,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "RAJENDRAKUMARJI DEVICHANDJI",
  },
  {
    hotiId: 152,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "RAJMALJI DANMALJI",
  },
  {
    hotiId: 153,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "RAMANKUMARJI MANCHALALJI",
  },
  {
    hotiId: 154,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 3,
    hotiName: "RAMESHCHANDJI LAXMICHANDJI MUTHA",
  },
  {
    hotiId: 155,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "RAMESHKUMARJI DANMALJI",
  },
  {
    hotiId: 156,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "RAMESHKUMARJI PHULCHANDJI",
  },
  {
    hotiId: 157,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "RAMESHKUMARJI HANSAJI KOTHARI",
  },
  {
    hotiId: 158,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "RAMESHKUMARJI JIVRAJJI-DIXIT",
  },
  {
    hotiId: 159,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 31,
    extraTicketQuota: 15,
    hotiName: "RAMESHKUMARJI KAPOORCHANDJI",
    contributionInRupees: 3100000,
    labhartiType: "Mukhya",
  },
  {
    hotiId: 160,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "RAMESHKUMARJI MANCHALALJI",
  },
  {
    hotiId: 161,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "RAMESHKUMARJI PUNMAJI KOTHARI",
  },
  {
    hotiId: 162,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "RAMESHKUMARJI UKCHANDJI KOTHARI",
  },
  {
    hotiId: 163,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "RAMESHKUMARJI VARDICHANDJI",
  },
  {
    hotiId: 164,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "RAMESHKUMARJI VIRCHANDJI",
  },
  {
    hotiId: 165,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "RATANCHANDJI PUNMAJI",
  },
  {
    hotiId: 166,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "RATANCHANDJI ASLAJI",
  },
  {
    hotiId: 167,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "RATANCHANDJI JAVERCHANDJI MUTHA",
  },
  {
    hotiId: 168,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 2,
    hotiName: "RIKABCHANDJI RATNAJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 169,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "RIKHABCHANDJI MANCHHALALJI",
  },
  {
    hotiId: 170,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "SAKALCHANDJI HANSAJI",
  },
  {
    hotiId: 171,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 2,
    hotiName: "SAKALCHANDJI GULALJI",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 172,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 5,
    hotiName: "SANGHVI  GENMALJI VARDICHANDJI",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 173,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 11,
    extraTicketQuota: 11,
    hotiName: "SANGHVI  GULABCHANDJI JAVERJI",
    contributionInRupees: 1100000,
    labhartiType: "Swarna",
  },
  {
    hotiId: 174,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 0,
    hotiName: "SANGHVI  KAPURCHANDJI MAGANLALJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 175,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 3,
    hotiName: "SANGHVI  FULCHANDJI VARDICHANDJI",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 176,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "SANGHVI  PITHALALJI SAKALAJI KOTHARI",
  },
  {
    hotiId: 177,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SANGHVI  PRITHVIRAJJI MAGANLALJI",
  },
  {
    hotiId: 178,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "SANGHVI SHANKARLALJI  JAVERJI",
  },
  {
    hotiId: 179,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 2,
    hotiName: "SANGHVI KESARIMALJI BABULALJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 180,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SHANKARLALJI DHARMAJI PORWAL",
  },
  {
    hotiId: 181,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SHANKARLALJI BHALAJI (BANSILAL)",
  },
  {
    hotiId: 182,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 10,
    hotiName: "SHANKARLALJI HUKMICHANDJI MUTHA",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 183,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "SHANKARLALJI HANSAJI MUTHA",
  },
  {
    hotiId: 184,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SHANTILALJI ASLAJI-MANOJ",
  },
  {
    hotiId: 185,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 5,
    hotiName: "SHANTILALJI GULABCHANDJI",
  },
  {
    hotiId: 186,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SHANTILALJI JAVERCHANDJI BHIRLOSHA",
  },
  {
    hotiId: 187,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "SHANTILALJI JORAJI",
  },
  {
    hotiId: 188,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SHANTILALJI MAGANLALJI",
  },
  {
    hotiId: 189,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 4,
    hotiName: "SHANTILALJI RATNAJI",
  },
  {
    hotiId: 190,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 3,
    hotiName: "SHANTILALJI SHANKARJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 191,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "SHANTILALJI BHIKHAJI BHIRLOSHA",
  },
  {
    hotiId: 192,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 1,
    hotiName: "SHIVLALJI BABULALJI",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 193,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SHIVLALJI KEWALCHANDJI  MUTHA",
  },
  {
    hotiId: 194,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "SHIVLALJI KESAJI",
  },
  {
    hotiId: 195,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SHIVLALJI PUNMAJI",
  },
  {
    hotiId: 196,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SOHANLALJI NATHMALJI",
  },
  {
    hotiId: 197,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SUKHRAJJI AMICHANDJI",
  },
  {
    hotiId: 198,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "SURESHKUMARJI HIRACHANDJI",
  },
  {
    hotiId: 199,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "SURESHKUMARJI KHETMALJI",
  },
  {
    hotiId: 200,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "SURESHKUMARJI PUNMAJI",
  },
  {
    hotiId: 201,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 3,
    hotiName: "SURESHKUMARJI UDAJI",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 202,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 0,
    hotiName: "SWARUPCHANDJI PHULCHANDJI",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 203,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "TARACHANDJI BHURAJI MUTHA",
  },
  {
    hotiId: 204,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "TARACHANDJI CHOGAJI",
  },
  {
    hotiId: 205,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "TARACHANDJI GULABCHANDJI",
  },
  {
    hotiId: 206,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "TARACHANDJI PUNMAJI MUTHA",
  },
  {
    hotiId: 207,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 11,
    extraTicketQuota: 3,
    hotiName: "TARACHANDJI SHIVLALJI METHA",
    contributionInRupees: 1100000,
    labhartiType: "Swarna",
  },
  {
    hotiId: 208,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "TEJRAJJI PUNMAJI KOTHARI",
  },
  {
    hotiId: 209,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "TEJPALJI PUNMAJI KOTHARI",
  },
  {
    hotiId: 210,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "UDAYRAJJI KHETMALJI",
  },
  {
    hotiId: 211,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "UKCHANDJI MULAJI",
  },
  {
    hotiId: 212,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 1,
    hotiName: "UKCHANDJI PITHAJI MUTHA",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 213,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "UKCHANDJI SHANKARLALJI",
  },
  {
    hotiId: 214,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "UKCHANDJI UDAJI MUTHA",
  },
  {
    hotiId: 215,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 5,
    extraTicketQuota: 6,
    hotiName: "UNMALJI KAPURJI BHIRLOSHA",
    contributionInRupees: 500000,
    labhartiType: "Rajat",
  },
  {
    hotiId: 216,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "UNMALJI LADAJI",
  },
  {
    hotiId: 217,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "VAGTAVARMALJI BABULALJI OSWAL",
  },
  {
    hotiId: 218,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "VARDICHANDJI ASLAJI",
  },
  {
    hotiId: 219,
    hotiTicketQuota: 0,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "VARDICHANDJI CHUNILALJI",
  },
  {
    hotiId: 220,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 2,
    hotiName: "VARDICHANDJI KEWALCHANDJI MUTHA",
  },
  {
    hotiId: 221,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "VARDICHANDJI PUNMAJI KOTHARI",
  },
  {
    hotiId: 222,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 1,
    hotiName: "VARDICHANDJI HIRAJI",
  },
  {
    hotiId: 223,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 1,
    extraTicketQuota: 2,
    hotiName: "VEERCHANDJI ASLAJI",
    contributionInRupees: 100000,
    labhartiType: "SahSahayak",
  },
  {
    hotiId: 224,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 3,
    extraTicketQuota: 0,
    hotiName: "VIRCHANDJI BHUBAJI",
    contributionInRupees: 300000,
    labhartiType: "Sahayak",
  },
  {
    hotiId: 301,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "CHAMPALALJI BADMERIYA",
  },
  {
    hotiId: 302,
    hotiTicketQuota: 2,
    labhartiTicketQuota: 0,
    extraTicketQuota: 0,
    hotiName: "RAJU BADMERIYA",
  },
];
